more CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,7 +25,7 @@ on:
 
 jobs:
   build:
-    name: build (${{ matrix.build_system }}, Fortran ${{ matrix.fortran }})
+    name: build (${{ matrix.build_system }}, Fortran ${{ matrix.fortran }}, compression ${{ matrix.compression }})
     runs-on: ubuntu-latest
     env:
       HDF5_PLUGIN_PATH: ${{ github.workspace }}/netcdf-c-install/hdf5/lib/plugin
@@ -35,6 +35,7 @@ jobs:
       matrix:
         build_system: [cmake, autotools]
         fortran: [on, off]
+        compression: [all, no-bzip2, no-lz4]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -224,7 +225,18 @@ jobs:
           if [ "${{ matrix.fortran }}" = "off" ]; then
             FORTRAN_FLAG="--disable-fortran"
           fi
-          ./configure --with-hdf5=$GITHUB_WORKSPACE/hdf5-install/bin/h5cc --enable-lz4 --enable-docs $FORTRAN_FLAG || (echo "Configure failed. Printing config.log:"; cat config.log; echo "hdf5_plugins/config.log:"; cat hdf5_plugins/config.log; exit 1)
+
+          BZIP2_FLAG=""
+          LZ4_FLAG="--enable-lz4"
+          if [ "${{ matrix.compression }}" = "no-bzip2" ]; then
+            BZIP2_FLAG="--disable-bzip2"
+            LZ4_FLAG="--enable-lz4"
+          elif [ "${{ matrix.compression }}" = "no-lz4" ]; then
+            BZIP2_FLAG=""
+            LZ4_FLAG="--disable-lz4"
+          fi
+
+          ./configure --with-hdf5=$GITHUB_WORKSPACE/hdf5-install/bin/h5cc $LZ4_FLAG $BZIP2_FLAG --enable-docs $FORTRAN_FLAG || (echo "Configure failed. Printing config.log:"; cat config.log; echo "hdf5_plugins/config.log:"; cat hdf5_plugins/config.log; exit 1)
 
       - name: Build (Autotools)
         if: matrix.build_system == 'autotools'
